name: build and push to GHCR

on:
  push:
    tags:
      - "*"
    branches:
      - "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # - name: Configure Git
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"

      # - name: Authenticate with GitHub
      #   run: |
      #     git remote set-url origin "https://x-access-token:${{ secrets.GHCR_PAT }}@github.com/${{ github.repository }}.git"

      # - name: Fetch all tags
      #   run: |
      #     # Ensure we have all tags locally
      #     git fetch --prune --tags

      # - name: Find and bump patch version
      #   id: version
      #   run: |
      #     # fetch all tags so we can see them locally
      #     git fetch --prune --unshallow --tags

      #     # find the latest semver tag (no leading v)
      #     LATEST_TAG=$(git tag --list --sort=v:refname | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | tail -n 1)

      #     if [ -z "$LATEST_TAG" ]; then
      #       # If no existing semver tags, start at 1.0.0
      #       NEW_TAG="1.0.0"
      #     else
      #       IFS='.' read -r MAJOR MINOR PATCH <<< "$LATEST_TAG"
      #       PATCH=$((PATCH + 1))
      #       NEW_TAG="${MAJOR}.${MINOR}.${PATCH}"
      #     fi

      #     echo "New tag: $NEW_TAG"
      #     echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      # - name: Create Git Tag Action
      #   uses: P4dr4/create-git-tag-action@v1.0.0
      #   with:
      #     tag_name: ${{ steps.version.outputs.NEW_TAG }}

      - name: Login to Docker Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Setup QEMU (for multi-platform builds)
        uses: docker/setup-qemu-action@v3

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ github.repository_owner }}/cookbook:latest
            ${{ github.repository_owner }}/cookbook:${{ steps.create_tag.outputs.tag_created }}
          file: ContainerFile
